/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export enum IntervalType {
  BIWEEKLY = "biweekly",
  DAILY = "daily",
  MONTHLY = "monthly",
  QUARTERLY = "quarterly",
  SEMIANNUAL = "semiannual",
  WEEKLY = "weekly",
  YEARLY = "yearly",
}

export enum NetworkType {
  BASE = "Base",
}

export enum StreamState {
  ACTIVE = "active",
  CANCELLED = "cancelled",
  INACTIVE = "inactive",
  PAUSED = "paused",
}

export enum Token {
  USDC = "USDC",
  USDT = "USDT",
}

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Numeric = ColumnType<number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface _PrismaMigrations {
  applied_steps_count: Generated<number>;
  checksum: string;
  finished_at: Timestamp | null;
  id: string;
  logs: string | null;
  migration_name: string;
  rolled_back_at: Timestamp | null;
  started_at: Generated<Timestamp>;
}

export interface Organization {
  admin: string;
  id: string;
  info: string;
  isDeployed: Generated<boolean>;
  isMigrated: Generated<boolean>;
  logo: string;
  name: string;
  network: NetworkType;
  owner: string;
  plugin: string;
  wallet: string;
}

export interface Schedule {
  active: Generated<boolean>;
  amount: Numeric;
  asset: Token;
  created_at: Generated<Timestamp>;
  id: string;
  interval: IntervalType;
  isOneTime: Generated<boolean>;
  network: NetworkType;
  nextPayout: Int8;
  org_id: string;
  payout: Generated<Numeric>;
  role: string;
  title: string;
  updated_at: Timestamp;
  username: string;
}

export interface Stream {
  active: Generated<boolean>;
  amount: Numeric;
  asset: Token;
  created_at: Generated<Timestamp>;
  id: string;
  interval: IntervalType;
  lastPayout: Generated<Int8>;
  network: NetworkType;
  org_id: string;
  payout: Generated<Numeric>;
  role: string;
  state: Generated<StreamState>;
  title: string;
  updated_at: Timestamp;
  username: string;
}

export interface Transaction {
  amount: Numeric;
  asset: Token;
  created_at: Generated<Timestamp>;
  network: NetworkType;
  org_id: string;
  recipient: string;
  schedule_id: string | null;
  stream_id: string | null;
  tx_id: string;
  username: string;
}

export interface User {
  email: string | null;
  image: string | null;
  name: string | null;
  total_payout: Generated<Numeric>;
  uid: string;
  username: string | null;
}

export interface Waitlist {
  company: string | null;
  email: string;
  name: string | null;
}

export interface Wallet {
  address: string;
  id: Generated<number>;
  network: NetworkType;
  username: string;
}

export interface DB {
  _prisma_migrations: _PrismaMigrations;
  organization: Organization;
  schedule: Schedule;
  stream: Stream;
  transaction: Transaction;
  user: User;
  waitlist: Waitlist;
  wallet: Wallet;
}
